function ejecutar(fondo){
    fondo=document.colors.c_fondos.value;
    texto=document.colors.c_texto.value;
    document.colors.res.style.bacground=fondo;
    document.colors.res.style.color=texto;
    if(fondo==1){
        r=document.colors.res.style.background="oranje"
    }
    if(fondo==2){
        r=document.colors.res.style.background="blue"
    }
    if(fondo==3){
        r=document.colors.res.style.background="green"
    }
    if(fondo==4){
        r=document.colors.res.style.background="purple"
    }
    if(fondo==5){
        r=document.colors.res.style.background="black"
    }
    if(texto==1){
        r=document.colors.res.style.color="oranje"
    }
    if(texto==2){
        r=document.colors.res.style.color="white"
    }
    if(texto==3){
        r=document.colors.res.style.color="black"
    }
    if(texto==4){
        r=document.colors.res.style.color="pink"
    }
    if(texto==5){
        r=document.colors.res.style.color="green"
    }
}